if(EXISTS "/home/runner/work/cpp_project_template/cpp_project_template/build/Release/test/unit_tests[1]_tests.cmake")
  include("/home/runner/work/cpp_project_template/cpp_project_template/build/Release/test/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
