name: Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

permissions:
  contents: write

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/configure
      with:
        build_type: ${{env.BUILD_TYPE}}

    - name: Build docs
      working-directory: ${{github.workspace}}/build/${{env.BUILD_TYPE}}
      run: |
        make docs
        sphinx-build -c . ${{github.workspace}}/docs .

    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build/${{env.BUILD_TYPE}}


    