name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install doxygen
        pip install conan
        conan install ${{github.workspace}} --build=missing -s build_type=${{env.BUILD_TYPE}} -pr:b=${{github.workspace}}/.conan/profiles/clang -pr:h=${{github.workspace}}/.conan/profiles/clang
        
    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: |
        . ./build/${{env.BUILD_TYPE}}/generators/conanbuild.sh
        cmake --preset conan-${{env.BUILD_TYPE},,}

    - name: Build tests
      working-directory: ${{github.workspace}}
      run: |
        . ./build/${{env.BUILD_TYPE}}/generators/conanbuild.sh
        cmake --build --preset conan-${{env.BUILD_TYPE},,} --target unit_tests
        
    - name: Run tests
      working-directory: ${{github.workspace}}/build/${{env.BUILD_TYPE}}
      run: |
        . ./generators/conanrun.sh
        ctest -V
